import { createHash, createHmac, randomUUID } from "node:crypto";
import { readFileSync, readdirSync } from "node:fs";
import { PGlite } from "@electric-sql/pglite";
import { pgcrypto } from "@electric-sql/pglite/contrib/pgcrypto";
import { afterAll, beforeAll, beforeEach, describe, expect, it } from "vitest";

const owner="11111111-1111-4111-8111-111111111111", key=Buffer.alloc(32,13);
const png=Buffer.from("iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mNk+A8AAQUBAScY42YAAAAASUVORK5CYII=","base64");
const imageDigest=createHash("sha256").update(png).digest("hex"); let db:PGlite;
function proof(operation:string,data:Record<string,unknown>){const message=JSON.stringify({version:1,user_id:owner,operation,expires:Math.floor(Date.now()/1000)+60,data});return[message,createHmac("sha256",key).update(message).digest("hex")]}
async function rpc(name:string,operation:string,data:Record<string,unknown>){return(await db.query<{v:unknown}>(`select public.${name}($1,$2) v`,proof(operation,data))).rows[0]?.v}
async function model(){await rpc("ai_save_local_model_configuration","save_local_model_configuration",{provider:"ollama",model:"vision-fixture",supports_image:true})}
type Cap="schoolScheduleImage.propose"|"blackboardCourseImage.propose";
const schedule=(courses:unknown[])=>({schema_version:1,type:"review_schedule_import",source_handle:"REPLACE",courses});
const blackboard=(courses:unknown[])=>({schema_version:1,type:"review_blackboard_courses",source_handle:"REPLACE",courses});
async function withHandle(proposal:Record<string,unknown>,capability:Cap){
  // Preparation creates the server handle before output exists. Build a valid
  // initial review by using a temporary flow split at its signed request.
  await model(); const image=await rpc("ai_create_validated_image","create_validated_image",{capability,normalized_base64:png.toString("base64"),normalized_digest:imageDigest,normalized_byte_count:png.length,width:1,height:1}) as string;
  const disclosure=await rpc("ai_prepare_image_disclosure","prepare_image_disclosure",{image_id:image,capability,provider:"ollama",model:"vision-fixture",location:"local",modality_source:"saved_local_configuration"}) as string;
  const request=await rpc("ai_prepare_school_screenshot","prepare_school_screenshot",{image_id:image,disclosure_id:disclosure,capability,provider:"ollama",model:"vision-fixture",location:"local",file_name:"fixture.png",time_zone:"Asia/Manila"}) as string;
  const handle=(await db.query<{source_handle:string}>("select source_handle from ai_scoped_requests where id=$1",[request])).rows[0].source_handle;
  const attempt=randomUUID(),payload="a".repeat(64); await rpc("ai_prepare_inference","prepare_inference",{id:attempt,checklist_request_id:null,course_request_id:null,scoped_request_id:request,parent_id:null,provider:"ollama",model:"vision-fixture",location:"local",capability,payload_digest:payload,text_bytes:100});
  await rpc("ai_claim_inference","claim_inference",{id:attempt,payload_digest:payload,consent:false});await rpc("ai_claim_image_disclosure","claim_image_disclosure",{disclosure_id:disclosure});await rpc("ai_finish_image_disclosure","finish_image_disclosure",{disclosure_id:disclosure,status:"succeeded"});
  const exact={...proposal,source_handle:handle};const batch=await rpc("ai_record_school_screenshot","record_school_screenshot",{request_id:request,proposal:exact}) as string;await rpc("ai_finish_inference","finish_inference",{id:attempt,status:"succeeded",error_code:null,batch_id:batch,latency_ms:1});return{request,batch,handle};
}
async function revise(batch:string,courses:unknown[]){return rpc("ai_revise_school_screenshot","revise_school_screenshot",{batch_id:batch,courses}) as Promise<string>}

describe("Pass 2C trusted screenshot consumers",()=>{
  beforeAll(async()=>{db=new PGlite({extensions:{pgcrypto}});await db.exec(`create role anon;create role authenticated;create role service_role bypassrls;create schema auth;create schema storage;create table auth.users(id uuid primary key);create function auth.uid() returns uuid language sql stable as $$select nullif(current_setting('request.jwt.claim.sub',true),'')::uuid$$;create function auth.role() returns text language sql stable as $$select current_setting('role',true)$$;grant usage on schema auth,public to authenticated,anon,service_role;grant execute on all functions in schema auth to authenticated,anon,service_role;alter default privileges in schema public grant all on tables to authenticated,service_role;create table storage.buckets(id text primary key,name text,public boolean,file_size_limit bigint);create table storage.objects(id uuid,name text,bucket_id text);`);for(const file of readdirSync("supabase/migrations").filter(x=>x.endsWith(".sql")).sort())await db.exec(readFileSync(`supabase/migrations/${file}`,"utf8"));await db.exec("grant all on all tables in schema public to service_role");await db.query("insert into ai_private.signing_key(secret) values($1)",[key]);await db.query("insert into auth.users(id) values($1)",[owner]);},60_000);
  afterAll(async()=>db?.close());
  beforeEach(async()=>{await db.exec("reset role;truncate ai_inference_attempts,operation_batches,ai_scoped_requests,ai_image_disclosures,ai_validated_images,ai_model_configurations,ai_preferences,course_meetings,courses cascade;set role authenticated");await db.query("select set_config('request.jwt.claim.sub',$1,false)",[owner]);});

  it("applies an exact edited Schedule successor and rejects its predecessor and replay",async()=>{const initial=await withHandle(schedule([{code:"CS101",name:"Detected",meetings:[{weekday:"monday",startTime:"09:00",endTime:"10:00"}],decision:"IGNORE"}]),"schoolScheduleImage.propose");const next=await revise(initial.batch,[{code:"CS101",name:"Edited name",meetings:[{weekday:"tuesday",startTime:"10:00",endTime:"11:00",room:"R1"}],decision:"CREATE_NEW"}]);await expect(rpc("ai_apply_school_schedule","approve_scoped:schoolScheduleImage.propose",{batch_id:initial.batch})).rejects.toThrow(/proposal_unavailable/);await rpc("ai_apply_school_schedule","approve_scoped:schoolScheduleImage.propose",{batch_id:next});expect((await db.query("select code,name from courses")).rows).toEqual([{code:"CS101",name:"Edited name"}]);expect((await db.query("select weekdays,start_time::text,location from course_meetings")).rows).toEqual([{weekdays:[2],start_time:"10:00:00",location:"R1"}]);await expect(rpc("ai_apply_school_schedule","approve_scoped:schoolScheduleImage.propose",{batch_id:next})).rejects.toThrow(/proposal_unavailable|request_unavailable/)});
  it("dedupes an existing slot through a fresh review and adds only a new actual meeting",async()=>{const first=await withHandle(schedule([{code:"CS101",name:"Course",meetings:[{weekday:"monday",startTime:"09:00",endTime:"10:00"}],decision:"IGNORE"}]),"schoolScheduleImage.propose");let next=await revise(first.batch,[{code:"CS101",name:"Course",meetings:[{weekday:"monday",startTime:"09:00",endTime:"10:00"}],decision:"CREATE_NEW"}]);await rpc("ai_apply_school_schedule","approve_scoped:schoolScheduleImage.propose",{batch_id:next});const course=(await db.query<{id:string}>("select id from courses")).rows[0].id;const second=await withHandle(schedule([{code:"CS101",name:"Course",meetings:[{weekday:"monday",startTime:"09:00",endTime:"10:00",room:"Changed display room"}],decision:"IGNORE"}]),"schoolScheduleImage.propose");next=await revise(second.batch,[{code:"CS101",name:"Course",meetings:[{weekday:"monday",startTime:"09:00",endTime:"10:00",room:"Changed display room"},{weekday:"wednesday",startTime:"11:00",endTime:"12:00"}],decision:"MATCH_EXISTING",targetCourseId:course}]);await rpc("ai_apply_school_schedule","approve_scoped:schoolScheduleImage.propose",{batch_id:next});expect((await db.query("select weekdays from course_meetings order by start_time")).rows).toEqual([{weekdays:[1]},{weekdays:[3]}])});
  it("fails stale exact Course targets and rejects Apply target substitution",async()=>{const id=(await db.query<{id:string}>("insert into courses(code,name) values('EX1','Existing') returning id")).rows[0].id;const initial=await withHandle(schedule([{code:"EX1",name:"Existing",meetings:[{weekday:"monday",startTime:"09:00",endTime:"10:00"}],decision:"IGNORE"}]),"schoolScheduleImage.propose");const next=await revise(initial.batch,[{code:"EX1",name:"Existing",meetings:[{weekday:"monday",startTime:"09:00",endTime:"10:00"}],decision:"MATCH_EXISTING",targetCourseId:id}]);await expect(rpc("ai_apply_school_schedule","approve_scoped:schoolScheduleImage.propose",{batch_id:next,targetCourseId:randomUUID()})).rejects.toThrow(/invalid_shape/);await db.query("update courses set name='Changed' where id=$1",[id]);await expect(rpc("ai_apply_school_schedule","approve_scoped:schoolScheduleImage.propose",{batch_id:next})).rejects.toThrow(/source_changed/)});
  it("rolls back all Schedule writes on a later conflict and denies suggest_only",async()=>{const initial=await withHandle(schedule([]),"schoolScheduleImage.propose");let next=await revise(initial.batch,[{code:"CPE201",name:"One",meetings:[{weekday:"monday",startTime:"09:00",endTime:"10:00"}],decision:"CREATE_NEW"},{code:"CPE 201",name:"Two",meetings:[{weekday:"tuesday",startTime:"09:00",endTime:"10:00"}],decision:"CREATE_NEW"}]);await expect(rpc("ai_apply_school_schedule","approve_scoped:schoolScheduleImage.propose",{batch_id:next})).rejects.toThrow(/course_conflict/);expect((await db.query("select * from courses")).rows).toHaveLength(0);await db.query("insert into ai_preferences(user_id,permission_mode) values($1,'suggest_only')",[owner]);const other=await withHandle(schedule([]),"schoolScheduleImage.propose");next=await revise(other.batch,[{code:"SAFE1",name:"Denied",meetings:[{weekday:"monday",startTime:"09:00",endTime:"10:00"}],decision:"CREATE_NEW"}]);await expect(rpc("ai_apply_school_schedule","approve_scoped:schoolScheduleImage.propose",{batch_id:next})).rejects.toThrow(/permission_denied/)});
  it("serializes concurrent Apply to one logical result",async()=>{const initial=await withHandle(schedule([]),"schoolScheduleImage.propose");const next=await revise(initial.batch,[{code:"CON1",name:"Concurrent",meetings:[{weekday:"monday",startTime:"09:00",endTime:"10:00"}],decision:"CREATE_NEW"}]);const results=await Promise.allSettled([rpc("ai_apply_school_schedule","approve_scoped:schoolScheduleImage.propose",{batch_id:next}),rpc("ai_apply_school_schedule","approve_scoped:schoolScheduleImage.propose",{batch_id:next})]);expect(results.filter(x=>x.status==="fulfilled")).toHaveLength(1);expect((await db.query("select * from courses")).rows).toHaveLength(1);expect((await db.query("select * from course_meetings")).rows).toHaveLength(1)});
  it("bootstraps Courses from label-only Blackboard extraction without creating mapping identity",async()=>{const initial=await withHandle(blackboard([{sourceLabel:"Visible label only",decision:"IGNORE"}]),"blackboardCourseImage.propose");const next=await revise(initial.batch,[{sourceLabel:"Visible label only",code:"CPE201",title:"Computer Engineering",decision:"CREATE_NEW"}]);await rpc("ai_apply_blackboard_bootstrap","approve_scoped:blackboardCourseImage.propose",{batch_id:next});expect((await db.query("select code,name from courses")).rows).toEqual([{code:"CPE201",name:"Computer Engineering"}]);expect((await db.query("select * from blackboard_course_mappings")).rows).toHaveLength(0)});
  it("uses exact Blackboard MATCH, rejects cross-capability reviews, and avoids second-import duplicates",async()=>{const existing=(await db.query<{id:string}>("insert into courses(code,name) values('CPE201','Existing') returning id")).rows[0].id;const initial=await withHandle(blackboard([{sourceLabel:"Ambiguous visible label",decision:"IGNORE"}]),"blackboardCourseImage.propose");const next=await revise(initial.batch,[{sourceLabel:"Ambiguous visible label",decision:"MATCH_EXISTING",targetCourseId:existing}]);await expect(rpc("ai_apply_school_schedule","approve_scoped:schoolScheduleImage.propose",{batch_id:next})).rejects.toThrow(/capability_denied/);await rpc("ai_apply_blackboard_bootstrap","approve_scoped:blackboardCourseImage.propose",{batch_id:next});expect((await db.query("select * from courses")).rows).toHaveLength(1)});
});
