import Link from "next/link";
import { AlertCircle, BookOpen, CalendarClock, CheckCircle2, NotebookPen } from "lucide-react";

import { Surface } from "@/components/ui/surface";
import type { CourseWithMeetings } from "@/types/course";
import type { Task } from "@/types/task";

import styles from "./home-dashboard.module.css";

function TaskList({tasks,empty}:{tasks:Task[];empty:string}){return tasks.length?<ul className={styles.list}>{tasks.slice(0,5).map(task=><li key={task.id}><span data-priority={task.priority}/><div><strong>{task.title}</strong><small>{task.dueAt?new Intl.DateTimeFormat(undefined,{hour:"numeric",minute:"2-digit"}).format(new Date(task.dueAt)):task.dueDate??task.status.replaceAll("_"," ")}</small></div></li>)}</ul>:<p className={styles.empty}>{empty}</p>}
export function HomeDashboard({today,overdue,upcoming,courses}:{today:Task[];overdue:Task[];upcoming:Task[];courses:CourseWithMeetings[]}){return <section className={styles.grid} aria-label="Home summary"><Surface variant="glass" className={`${styles.card} ${styles.today}`}><header><span><CalendarClock size={18}/></span><div><p>Today</p><h2>{today.length?`${today.length} item${today.length===1?"":"s"}`:"Clear schedule"}</h2></div><Link href="/tasks?view=today">Open</Link></header><TaskList tasks={today} empty="Nothing is due or scheduled today."/></Surface><Surface variant="base" className={styles.card}><header><span><AlertCircle size={18}/></span><div><p>Overdue</p><h2>{overdue.length?`${overdue.length} need attention`:"All caught up"}</h2></div><Link href="/tasks?view=overdue">Review</Link></header><TaskList tasks={overdue} empty="No overdue work."/></Surface><Surface variant="base" className={styles.card}><header><span><CheckCircle2 size={18}/></span><div><p>Upcoming</p><h2>Next seven days</h2></div><Link href="/tasks?view=next7">View</Link></header><TaskList tasks={upcoming.filter(task=>!today.some(item=>item.id===task.id))} empty="Nothing upcoming."/></Surface><Surface variant="base" className={styles.card}><header><span><BookOpen size={18}/></span><div><p>School</p><h2>{courses.length?`${courses.length} active ${courses.length===1?"course":"courses"}`:"No courses yet"}</h2></div><Link href="/school">Open</Link></header>{courses.length?<ul className={styles.courses}>{courses.slice(0,4).map(course=><li key={course.id}><span style={{background:course.color??"var(--accent)"}}/><div><strong>{course.code}</strong><small>{course.meetings.length} weekly {course.meetings.length===1?"meeting":"meetings"}</small></div></li>)}</ul>:<p className={styles.empty}>Add courses and their weekly timetable in School.</p>}</Surface><Surface variant="subtle" className={`${styles.card} ${styles.note}`}><NotebookPen size={22}/><div><h2>Capture a quick note</h2><p>Write in Markdown and link the note to a task or course.</p></div><Link href="/notes">New note</Link></Surface></section>}

