import { NextResponse } from "next/server";

import { requireAuthenticatedSupabase } from "@/services/supabase/request";

export const runtime="nodejs";const BUCKET="private-attachments";
function sameOrigin(request:Request){const origin=request.headers.get("origin");return !origin||origin===new URL(request.url).origin;}
function cleanName(value:string){return value.normalize("NFKC").replace(/[\\/\0-\x1f\x7f]/g,"-").trim().slice(0,180)||"attachment";}
function safeFailure(error:unknown){console.error("[attachments] item request failed:",error);return NextResponse.json({message:"The attachment request could not be completed."},{status:500});}
async function owned(id:string){const{client,userId}=await requireAuthenticatedSupabase();const result=await client.from("attachments").select("id,file_name,storage_path").eq("id",id).eq("user_id",userId).maybeSingle();if(result.error)throw result.error;return{client,row:result.data};}
export async function GET(_request:Request,context:RouteContext<"/api/attachments/[id]">){try{const{id}=await context.params;const{client,row}=await owned(id);if(!row)return NextResponse.json({message:"Attachment not found."},{status:404});const signed=await client.storage.from(BUCKET).createSignedUrl(row.storage_path,60,{download:row.file_name});if(signed.error)throw signed.error;return NextResponse.redirect(signed.data.signedUrl,{status:302,headers:{"Cache-Control":"no-store","Referrer-Policy":"no-referrer"}});}catch(error){return safeFailure(error);}}
export async function PATCH(request:Request,context:RouteContext<"/api/attachments/[id]">){if(!sameOrigin(request))return NextResponse.json({message:"Invalid request origin."},{status:403});try{const{id}=await context.params;const body=await request.json() as{fileName?:unknown};if(typeof body.fileName!=="string")return NextResponse.json({message:"Choose a file name."},{status:400});const{client,row}=await owned(id);if(!row)return NextResponse.json({message:"Attachment not found."},{status:404});const{error}=await client.from("attachments").update({file_name:cleanName(body.fileName)}).eq("id",id).select("id").single();if(error)throw error;return NextResponse.json({ok:true});}catch(error){return safeFailure(error);}}
export async function DELETE(request:Request,context:RouteContext<"/api/attachments/[id]">){if(!sameOrigin(request))return NextResponse.json({message:"Invalid request origin."},{status:403});try{const{id}=await context.params;const{client,row}=await owned(id);if(!row)return NextResponse.json({message:"Attachment not found."},{status:404});const removed=await client.storage.from(BUCKET).remove([row.storage_path]);if(removed.error)throw removed.error;const deleted=await client.from("attachments").delete().eq("id",id).select("id").maybeSingle();if(deleted.error)throw deleted.error;return NextResponse.json({ok:true});}catch(error){return safeFailure(error);}}

