import { describe,expect,it } from "vitest";

import { isQuietHours,notificationDedupeKey,pushAvailability,safeDeepLink,safeNotificationPayload } from "@/services/notifications/notification-domain";
import { parseBlackboardICalendar } from "./ical";
import { isPublicAddress,validateFeedUrl } from "./safe-url";
import { matchBlackboardCourse,planBlackboardSync,type ExistingBlackboardRecord } from "./sync-domain";

const feed=`BEGIN:VCALENDAR\r\nBEGIN:VEVENT\r\nUID:item-1\r\nSUMMARY:[CS101] Essay\r\nDESCRIPTION:Read\\nWrite\r\nDTEND:20300102T090000Z\r\nLAST-MODIFIED:20300101T010000Z\r\nURL:https://learn.example.edu/item/1\r\nEND:VEVENT\r\nEND:VCALENDAR`;
describe("Blackboard iCalendar",()=>{it("parses stable identity, deadline, source, and course",()=>{const[item]=parseBlackboardICalendar(feed);expect(item).toMatchObject({uid:"item-1",title:"[CS101] Essay",courseCode:"CS101",dueAt:"2030-01-02T09:00:00.000Z",sourceUrl:"https://learn.example.edu/item/1"});expect(item.contentHash).toHaveLength(64);});it("uses deterministic fallback identity without merging different deadlines",()=>{const a=parseBlackboardICalendar(feed.replace("UID:item-1\r\n","").replace("DTEND:20300102","DTEND:20300103"))[0];const b=parseBlackboardICalendar(feed.replace("UID:item-1\r\n","").replace("DTEND:20300102","DTEND:20300104"))[0];expect(a.uid).toMatch(/^fallback:/);expect(a.uid).not.toBe(b.uid);});});
describe("Blackboard sync plan",()=>{const item=parseBlackboardICalendar(feed)[0];const existing:ExistingBlackboardRecord={id:"r1",externalUid:item.uid,contentHash:"old",taskId:"t1",missingSince:null,task:{title:"Personal title",description:"Personal notes stay elsewhere",dueAt:null,dueDate:null,status:"submitted",priority:"urgent",scheduledStart:"2030-01-01T01:00:00Z",scheduledEnd:"2030-01-01T02:00:00Z"}};it("deduplicates repeated feed items and changes provider fields only",()=>{const plan=planBlackboardSync([item,item],[existing],"Asia/Manila");expect(plan.creates).toHaveLength(0);expect(plan.updates).toHaveLength(1);expect(plan.updates[0].taskPatch.dueAt).toBe(item.dueAt);expect(plan.updates[0].taskPatch).not.toHaveProperty("status");expect(plan.updates[0].taskPatch).not.toHaveProperty("priority");expect(plan.updates[0].taskPatch).not.toHaveProperty("scheduledStart");});it("is unchanged on idempotent retry",()=>{expect(planBlackboardSync([item],[{...existing,contentHash:item.contentHash}],"Asia/Manila").unchanged).toHaveLength(1);});it("marks disappeared records missing rather than deleting",()=>{const plan=planBlackboardSync([], [existing],"Asia/Manila");expect(plan.missing).toEqual([existing]);});it("does not silently resolve ambiguous courses",()=>{expect(matchBlackboardCourse("CS101",[{id:"a",code:"CS101",name:"One"},{id:"b",code:"CS-101",name:"Two"}],{}).kind).toBe("ambiguous");});});
describe("SSRF and credential redaction boundaries",()=>{it.each(["127.0.0.1","10.0.0.1","169.254.169.254","192.168.1.1","::1","fc00::1"])("rejects private address %s",address=>expect(isPublicAddress(address)).toBe(false));it("requires standard credential-free HTTPS",()=>{expect(()=>validateFeedUrl("http://learn.example.edu/feed")).toThrow();expect(()=>validateFeedUrl("https://user:secret@learn.example.edu/feed")).toThrow();expect(validateFeedUrl("https://learn.example.edu/feed").hostname).toBe("learn.example.edu");});it("redacts URLs from notification payloads",()=>expect(safeNotificationPayload({title:"Update",body:"Open https://private.example/token",deepLink:"/tasks",dedupeKey:"x"}).body).not.toContain("private.example"));});
describe("notification rules",()=>{it("deduplicates persistently and validates deep links",()=>{expect(notificationDedupeKey("blackboard_assignment","1","a")).toBe(notificationDedupeKey("blackboard_assignment","1","a"));expect(safeDeepLink("https://evil.example")).toBe("/");expect(safeDeepLink("/tasks?view=today")).toBe("/tasks?view=today");});it("respects overnight quiet hours",()=>{expect(isQuietHours(new Date("2030-01-01T15:30:00Z"),"Asia/Manila","22:00","07:00")).toBe(true);expect(isQuietHours(new Date("2030-01-01T04:00:00Z"),"Asia/Manila","22:00","07:00")).toBe(false);});it("reports unavailable iPhone push honestly",()=>{expect(pushAvailability({serviceWorker:true,pushManager:true,standalone:false,isIOS:true,vapidKey:true})).toEqual({available:false,reason:"install_required"});});});
