import "server-only";

import { lookup } from "node:dns/promises";
import { request } from "node:https";
import { isPublicAddress, validateFeedUrl } from "./safe-url";

const MAX_BYTES=2_000_000;const MAX_REDIRECTS=3;
export class BlackboardFetchError extends Error{constructor(readonly code:string,message:string){super(message);this.name="BlackboardFetchError";}}
async function resolved(url:URL){const answers=await lookup(url.hostname,{all:true,verbatim:true});if(!answers.length||answers.some(answer=>!isPublicAddress(answer.address)))throw new BlackboardFetchError("unsafe_dns","The feed host resolves to a private or reserved address.");return answers[0];}
async function one(url:URL):Promise<{status:number;headers:Record<string,string|string[]|undefined>;body:string}>{const target=await resolved(url);return new Promise((resolve,reject)=>{const req=request(url,{method:"GET",headers:{Accept:"text/calendar, application/ics;q=0.9","User-Agent":"Life-OS-Blackboard-Sync/1"},lookup:(_host,_options,callback)=>callback(null,target.address,target.family)},response=>{const chunks:Buffer[]=[];let size=0;response.on("data",chunk=>{size+=chunk.length;if(size>MAX_BYTES){req.destroy(new BlackboardFetchError("response_too_large","The Blackboard feed exceeds the size limit."));return;}chunks.push(chunk);});response.on("end",()=>resolve({status:response.statusCode??0,headers:response.headers,body:Buffer.concat(chunks).toString("utf8")}));});req.setTimeout(10_000,()=>req.destroy(new BlackboardFetchError("timeout","Blackboard did not respond in time.")));req.on("error",reject);req.end();});}
export async function fetchBlackboardCalendar(value:string){let url=validateFeedUrl(value);for(let redirect=0;redirect<=MAX_REDIRECTS;redirect++){const response=await one(url);if(response.status>=300&&response.status<400){const location=Array.isArray(response.headers.location)?response.headers.location[0]:response.headers.location;if(!location||redirect===MAX_REDIRECTS)throw new BlackboardFetchError("redirect","The Blackboard feed redirected unsafely.");url=validateFeedUrl(new URL(location,url).toString());continue;}if(response.status!==200)throw new BlackboardFetchError("http_status","Blackboard returned an unsuccessful response.");const type=String(response.headers["content-type"]??"").toLowerCase();if(type&&!type.includes("text/calendar")&&!type.includes("application/ics")&&!type.includes("text/plain"))throw new BlackboardFetchError("content_type","Blackboard returned an unexpected content type.");if(!response.body.includes("BEGIN:VCALENDAR"))throw new BlackboardFetchError("invalid_calendar","Blackboard returned an invalid calendar.");return response.body;}throw new BlackboardFetchError("redirect","The Blackboard feed redirected too many times.");}
